USE p02;

CREATE TABLE noticias (
  id INT AUTO_INCREMENT PRIMARY KEY,
  title VARCHAR(255) NOT NULL,
  date DATE NOT NULL,
  author VARCHAR(255) NOT NULL,
  url VARCHAR(255),
  content TEXT NOT NULL,
  image LONGBLOB,
  category VARCHAR(50) NOT NULL
);
